### Essential NumPy and Pandas Functions for Data Analysis

Let's look at practical code snippets that demonstrate the most useful NumPy and pandas methods for data analysis in Python. You can use these in a Jupyter notebook for experimentation and workflow mastery.

#### NumPy Basics for Data Analysis
Import NumPy:

In [6]:
import numpy as np

1. Creating Arrays

In [7]:
arr = np.array([1, 2, 3, 4])            # 1D array
matrix = np.array([[1, 2], [3, 4]])     # 2D array
zeros = np.zeros((2, 3))                # 2x3 array of zeros
ones = np.ones((2, 3))                  # 2x3 array of ones
rnd = np.random.rand(2, 3)              # 2x3 array of random floats

2. Array Shape, Reshape, Flatten

In [8]:
print(arr.shape)                # (4,)
reshaped = matrix.reshape((4, 1))   # Reshape to 4 rows, 1 column
flat = matrix.ravel()               # Flatten to 1D array

(4,)

3. Indexing and Slicing

In [9]:
print(matrix[0, 1])    # element at first row, second column
print(arr[1:3])        # slice elements 1 to 2

2
[2 3]

4. Basic Math Operations

In [13]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)           # [11 22 33]
print(a - b)           # [ 9 18 27]
print(a * b)           # [10 40 90]
print(a / b)           # [10. 10. 10.]

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]

5. Aggregation and Stats

In [15]:
np.sum(arr)                 # 10
np.mean(arr)                # 2.5
np.std(arr)                 # Standard deviation
np.min(arr), np.max(arr)    # Min and max values

(np.int64(1), np.int64(4))

6. Dot Product, Matrix Ops

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)          # 1*4 + 2*5 + 3*6 = 32
mat = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matprod = np.matmul(mat, mat2) # Matrix multiplication

7. Logical and Filtering

In [ ]:
arr[arr > 2]                # Returns [3, 4]
np.where(arr > 2)           # Indices where condition is true

(array([2, 3], dtype=int64),)

8. Random Sampling

In [ ]:
np.random.randint(0, 100, size=5) # 5 random ints 0-99
np.random.choice([0, 1], size=10) # 10 random 0s or 1s

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0])

#### Pandas Basics for Data Analysis
Import pandas:

In [ ]:
import pandas as pd

1. Creating DataFrames

In [ ]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data) # Create DataFrame

2. Inspecting Data

In [ ]:
df.head()                # First 5 rows
df.tail(3)                # Last 3 rows
df.info()                 # DataFrame info + datatypes
df.describe()             # Summary statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

         A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

3. Selecting Data

In [ ]:
df['A']                   # Get column A
df.loc[0]                 # Row by label (index 0)
df.iloc[1:3]              # Rows 1-2 by position
df[df['A'] > 1]           # Filter rows where A > 1

   A  B
1  2  5
2  3  6

4. Adding/Dropping Columns

In [ ]:
df['C'] = df['A'] + df['B']     # Add new column
new_df = df.drop('B', axis=1)   # Drop column B

5. Missing Values & Types

In [ ]:
df.isnull().sum()               # Missing values per column
df.fillna(0)                    # Replace NaNs with 0
df['A'] = df['A'].astype(float) # Change column type

6. Grouping and Aggregation

In [ ]:
grouped = df.groupby('A').sum()   # Sum columns, grouped by values in A
df['A'].value_counts()            # Count unique values in A

A
1.0    1
2.0    1
3.0    1
Name: count, dtype: int64

7. Sorting

In [ ]:
df.sort_values('B', ascending=False)  # Sort by column B

     A  B  C
2  3.0  6  9
1  2.0  5  7
0  1.0  4  5

8. Reading/Writing Files

In [ ]:
df.to_csv('mydata.csv') # Save to CSV
df = pd.read_csv('mydata.csv') # Load from CSV
df.head()

   Unnamed: 0    A  B  C
0           0  1.0  4  5
1           1  2.0  5  7
2           2  3.0  6  9

9. Apply/Map Functions

In [ ]:
df['A_squared'] = df['A'].apply(lambda x: x**2) # Apply to column
df['B_label'] = df['B'].map({4: 'Low', 5: 'Med', 6: 'High'}) # Map values
df.sample(3)

   Unnamed: 0    A  B  C  A_squared B_label
0           0  1.0  4  5        1.0     Low
1           1  2.0  5  7        4.0     Med
2           2  3.0  6  9        9.0    High

### Task:

- Generated a Synthetic Dataset with columns of `age`, `salary`, `department`, `years_experience`, and `is_manager`.

In [17]:
import pandas as pd
import numpy as np

np.random.seed(42) # For reproducibility
n_samples = 100 # Number of samples

data = {
    'age': np.random.randint(18, 60, size=n_samples),
    'salary': np.random.randint(30000, 120000, size=n_samples),
    'department': np.random.choice(['IT', 'HR', 'Finance', 'Marketing'], size=n_samples),
    'years_experience': np.round(np.random.normal(5, 2, size=n_samples), 1),
    'is_manager': np.random.choice([0, 1], size=n_samples)
}
df = pd.DataFrame(data)

Q1. View data structure

In [18]:
print(df)

    age  salary department  years_experience  is_manager
0    56   38392         IT              -0.8           0
1    46   60535  Marketing               3.4           1
2    32  108603         HR               5.0           1
3    25   82256         HR               4.2           1
4    38  119135         HR               4.1           1
..  ...     ...        ...               ...         ...
95   59   82662         IT               4.0           0
96   56   42688         HR               4.4           1
97   58   55342  Marketing               6.0           0
98   45   67157         HR              11.4           0
99   24   97863         HR               5.2           1

[100 rows x 5 columns]

Q2. Get DataFrame Info and Summary Stats

In [19]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               100 non-null    int64
 1   salary            100 non-null    int64
 2   department        100 non-null    object
 3   years_experience  100 non-null    float64
 4   is_manager        100 non-null    int64
dtypes: float64(1), int64(3), object(1)
memory usage: 4.0+ KB

              age         salary  years_experience  is_manager
count  100.000000     100.000000        100.000000  100.000000
mean    37.910000   77809.160000          4.823000    0.470000
std     12.219454   26058.643576          2.237822    0.501614
min     18.000000   30206.000000         -0.800000    0.000000
25%     26.750000   55141.000000          3.475000    0.000000
50%     38.000000   80932.000000          4.700000    0.000000
75%     46.250000   98107.250000          6.000000    1.000000
max     59.000000  119474.000000         11.400000    1.000000

Q3. Do Simple Numpy Operations

In [20]:
a = np.array([[10, 20, 30],[22,4,5]])
b = np.array([[1, 2, 3],[2,4,2]])
print(a + b)
print(a - b) 
print(a * b) 
print(a / b)

[[11 22 33]
 [24  8  7]]
[[ 9 18 27]
 [20  0  3]]
[[10 40 90]
 [44 16 10]]
[[10.  10.  10. ]
 [11.   1.   2.5]]

Q4. Filtering and Indexing Rows

In [26]:
a = np.array([[10, 20, 30],[22,4,5]])
print(a)
print(a[1,2])
print(a[0:1])
print(a[a>9])

[[10 20 30]
 [22  4  5]]
5
[[10 20 30]]
[10 20 30 22]

Q5. Adding a Column

In [29]:
df['City'] = np.random.choice(['Delhi', 'Mumbai', 'Kolkata', 'Chennai'], size = len(df))
print(df)

    age  salary department  years_experience  is_manager     City
0    56   38392         IT              -0.8           0    Delhi
1    46   60535  Marketing               3.4           1  Chennai
2    32  108603         HR               5.0           1    Delhi
3    25   82256         HR               4.2           1  Chennai
4    38  119135         HR               4.1           1  Chennai
..  ...     ...        ...               ...         ...      ...
95   59   82662         IT               4.0           0  Kolkata
96   56   42688         HR               4.4           1   Mumbai
97   58   55342  Marketing               6.0           0  Chennai
98   45   67157         HR              11.4           0    Delhi
99   24   97863         HR               5.2           1   Mumbai

[100 rows x 6 columns]

Q6. Grouping and Aggregation

In [30]:
grouped = df.groupby('age').sum() 
df['age'].value_counts()

age
41    6
25    5
56    4
42    4
32    4
38    4
31    4
24    4
19    4
52    3
43    3
21    3
35    3
26    3
45    3
46    3
59    3
28    3
57    3
53    3
34    2
18    2
58    2
33    2
39    2
20    2
50    2
40    2
48    1
27    1
51    1
23    1
29    1
36    1
37    1
54    1
47    1
55    1
44    1
22    1
Name: count, dtype: int64